services:
  db:
    build:
      context: db
      dockerfile: Dockerfile
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: sampledb
    ports:
      - "5432:5432"
    volumes:
      - data_sql:/var/lib/postgresql/data
  app:
    build:
      context: src
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./src:/app
    # environment:
    #   DATABASE_URL: postgresql://postgres:mysecretpassword@db:5432/sampledb

volumes:
  data_sql: